### PR TITLE
Can you please make the similar scripts comparable?

### PR DESCRIPTION
**Pull request by yhfudev**
Hi,
I'm trying to compile images for both rpi2 and odroidc1 recently, and found the scripts you used here. In order to support those new hardware, a new script need to be developed base on yours, and it would be better if your scripts are changed more similar with each other so the other developers can easily identify the differences and free from the mistake cause the every detail of the compile issue.

Also, could you please consider upgrade your scripts to more stable compile platform? I tried to use Arch like tools to manage the compile scripts so that the compile process benefit from the support features of "automatically download and install prerequisites", "automatically download, setup, and cache source/tool trees", "deb file cache", and "debootstrip stage cache" etc. You may take a look the project in github:
https://github.com/yhfudev/arch-kali-rpi2

It use a single PKGBUILD file to config the image, and other functions will be provided by the framework, so adding support for a new hardware is a trival work due to reuse of codes.

The arch-kali-rpi2 can now support runing X window in Raspberry Pi 2, I fixed the problems caused by the modules mismatch without using the modules from old debian image.

### CODE REVIEW

**Comment by cyrus104** [comment]
Have you come up with a good solution for the odroid-c1?

**Comment by yhfudev** [comment]
No yet, I'm still waiting for the HDMI cable to connect my monitor and I'll
test the image I created once I get it.
I'll let you know if it done.

**Comment by cyrus104** [comment]
I did find your odroid script and I'm super hopeful that it works. I've been waiting for Offensive-Security to add support for the odroid-c1 for awhile.

Thanks

**Comment by yhfudev** [comment]
Could you please test it with X window? since the framework also works for
Raspberry Pi 2.
I did compile it and got a image file.

**Comment by cyrus104** [comment]
I'm having some issues with the build"

Build U-Boot ...
[DBG]
PATH=/home/dade/arch-kali-odroidc1/src//toolchains-uboot-armhf/gcc-linaro-arm-none-eabi-4.8-2014.04_linux/bin/:/home/dade/arch-kali-odroidc1/src//toolchains-kernel-armhf/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux/bin/:/home/dade/arch-kali-odroidc1/src//toolchains-kernel-armhf/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux/bin/:/home/dade/bin:/sbin/:/usr/sbin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
awk '(NF && $1 !~ /^#/) { print $1 ": " $1 "_config; $(MAKE)" }' boards.cfg
board/amlogic/boards.cfg customer/board/boards.cfg >
/home/dade/arch-kali-odroidc1/src/uboot-hardkernel-git/build/.boards.depend
/home/dade/arch-kali-odroidc1/src/uboot-hardkernel-git/mkconfig -A odroidc
odroidc arm aml_meson odroidc hardkernel m8b hardkernel/odroidc:DDR3_1GB
Configuring for odroidc - Board: hardkernel/odroidc, Options: DDR3_1GB




/bin/sh: 1: arm-linux-gnueabihf-gcc: not found
scripts/Makefile.build:308: recipe for target 'scripts/mod/empty.o' failed
make[2]: *** [scripts/mod/empty.o] Error 127
scripts/Makefile.build:455: recipe for target 'scripts/mod' failed
make[1]: *** [scripts/mod] Error 2
make[1]: *** Waiting for unfinished jobs....
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/dtc/util.o
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  Generating include/generated/mach-types.h
  CC      kernel/bounds.s
/bin/sh: 1: arm-linux-gnueabihf-gcc: not found
/home/dade/arch-kali-odroidc1/src/linux-hardkernel-git/./Kbuild:35: recipe
for target 'kernel/bounds.s' failed
make[1]: *** [kernel/bounds.s] Error 127
Makefile:837: recipe for target 'prepare0' failed
make: *** [prepare0] Error 2
make: *** Waiting for unfinished jobs....
  HOSTLD  scripts/dtc/dtc
Makefile:518: recipe for target 'scripts' failed
make: *** [scripts] Error 2
Error in compiling linux kernel

**Comment by yhfudev** [comment]
Two reasons may caused the problem:

1) the PATH environment was not set
2) your host is installed 64 bit system, while the 32 bit libs were not
installed. The toolchain is 32bit.

It seems it is the second reason.

I'm sorry the build script didn't detect the correct lib, I updated repo
and you may try it again.

The project is not stable, and I'm still working on this project.

**Comment by cyrus104** [comment]
Understood, so far so good.

Glad someone is working on this as I like the odroid-c1.

**Comment by cyrus104** [comment]
The build completed however now it didn't boot. I tried to copy the image
over two times. The odroid keeps a black screen when it's powered on.

**Pull request closed without merging**
